export const data = [
  {
    video: "JfVOs4VSpmA",
    adult: false,
    backdrop_path: "/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    popularity: 6008.145,
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    release_date: "2021-12-15",
    title: "Spider-Man: No Way Home",

    vote_average: 8.3,
    vote_count: 8776,
  },
  {
    video: "mqqft2x_Aa4",
    adult: false,
    backdrop_path: "/5P8SmMzSNYikXpxil6BYzJ16611.jpg",
    genre_ids: [28, 80, 18],
    id: 414906,
    original_language: "en",
    original_title: "The Batman",
    overview:
      "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
    popularity: 4598.244,
    poster_path: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    release_date: "2022-03-01",
    title: "The Batman",

    vote_average: 8.2,
    vote_count: 666,
  },
  {
    video: "CaimKeDcudo",
    adult: false,
    backdrop_path: "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
    genre_ids: [16, 35, 10751, 14],
    id: 568124,
    original_language: "en",
    original_title: "Encanto",
    overview:
      "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
    popularity: 3098.533,
    poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
    release_date: "2021-11-24",
    title: "Encanto",

    vote_average: 7.7,
    vote_count: 4985,
  },
  {
    video: "5ra0G49uF-4",
    adult: false,
    backdrop_path: "/4OTYefcAlaShn6TGVK33UxLW9R7.jpg",
    genre_ids: [28, 12, 53, 10752],
    id: 476669,
    original_language: "en",
    original_title: "The King's Man",
    overview:
      "As a collection of history's worst tyrants and criminal masterminds gather to plot a war to wipe out millions, one man must race against time to stop them.",
    popularity: 2212.212,
    poster_path: "/aq4Pwv5Xeuvj6HZKtxyd23e6bE9.jpg",
    release_date: "2021-12-22",
    title: "The King's Man",

    vote_average: 7.1,
    vote_count: 1709,
  },
  {
    video: "beToTslH17s",
    adult: false,
    backdrop_path: "/usaZV7KB6Man9Rm9TyDAeQf7uVD.jpg",
    genre_ids: [27, 9648, 53],
    id: 646385,
    original_language: "en",
    original_title: "Scream",
    overview:
      "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
    popularity: 2107.097,
    poster_path: "/kZNHR1upJKF3eTzdgl5V8s8a4C3.jpg",
    release_date: "2022-01-12",
    title: "Scream",

    vote_average: 6.9,
    vote_count: 789,
  },
  {
    video: "_Gr2zXuEBL0",
    adult: false,
    backdrop_path: "/mruT954ve6P1zquaRs6XG0hA5k9.jpg",
    genre_ids: [53],
    id: 800510,
    original_language: "en",
    original_title: "Kimi",
    overview:
      "A tech worker with agoraphobia discovers recorded evidence of a violent crime but is met with resistance when she tries to report it. Seeking justice, she must do the thing she fears the most: she must leave her apartment.",
    popularity: 1901.77,
    poster_path: "/okNgwtxIWzGsNlR3GsOS0i0Qgbn.jpg",
    release_date: "2022-02-10",
    title: "Kimi",
    vote_average: 6.3,
    vote_count: 188,
  },
  {
    video: "Q81Yf46Oj3s",
    adult: false,
    backdrop_path: "/mqDnDhG5N6fn1H4MKQqr8E5wfeK.jpg",
    genre_ids: [80, 18, 53],
    id: 597208,
    original_language: "en",
    original_title: "Nightmare Alley",
    overview:
      "An ambitious carnival man with a talent for manipulating people with a few well-chosen words hooks up with a female psychiatrist who is even more dangerous than he is.",
    popularity: 1780.458,
    poster_path: "/680klE0dIreQQOyWKFgNnCAJtws.jpg",
    release_date: "2021-12-02",
    title: "Nightmare Alley",
    vote_average: 7.1,
    vote_count: 931,
  },
  {
    video: "Pj0wz7zu3Ms",
    adult: false,
    backdrop_path: "/dK12GIdhGP6NPGFssK2Fh265jyr.jpg",
    genre_ids: [28, 35, 80, 53],
    id: 512195,
    original_language: "en",
    original_title: "Red Notice",
    overview:
      "An Interpol-issued Red Notice is a global alert to hunt and capture the world's most wanted. But when a daring heist brings together the FBI's top profiler and two rival criminals, there's no telling what will happen.",
    popularity: 1771.219,
    poster_path: "/wdE6ewaKZHr62bLqCn7A2DiGShm.jpg",
    release_date: "2021-11-04",
    title: "Red Notice",
    vote_average: 6.8,
    vote_count: 3164,
  },
];
